version: '3'

services:
  mysql:
    container_name: mysql5.7
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data/mysql:/var/lib/mysql
