version: '3'

services:
  etcd-standalone:
    container_name: etcd-standalone
    image: quay.io/coreos/etcd:v3.5.1
    ports:
      - '2379:2379'
      - '2380:2380'
    volumes:
      - './data/etcd-standalone/:/etcd-data'
      - ./config/etcd-standalone.yml:/config.yml
    command: etcd --config-file /config.yml
