version: '3'

services:
  etcd-cluster-node1:
    container_name: etcd-cluster-node1
    image: quay.io/coreos/etcd:v3.5.1
    ports:
      - '12379:2379'
      - '12380:2380'
    volumes:
      - './data/etcd-cluster-node1/:/etcd-data'
      - ./config/etcd-cluster-node1.yml:/config.yml
    command: etcd --config-file /config.yml

  etcd-cluster-node2:
    container_name: etcd-cluster-node2
    image: quay.io/coreos/etcd:v3.5.1
    ports:
      - '22379:2379'
      - '22380:2380'
    volumes:
      - './data/etcd-cluster-node2/:/etcd-data'
      - ./config/etcd-cluster-node2.yml:/config.yml
    command: etcd --config-file /config.yml

  etcd-cluster-node3:
    container_name: etcd-cluster-node3
    image: quay.io/coreos/etcd:v3.5.1
    ports:
      - '32379:2379'
      - '32380:2380'
    volumes:
      - './data/etcd-cluster-node3/:/etcd-data'
      - ./config/etcd-cluster-node3.yml:/config.yml
    command: etcd --config-file /config.yml
